# ==================================
# === 模擬與模型設定 (Simulation & Model Settings)
# ==================================
# 檔案路徑 (File Paths)
mujoco_model_file: "assets/scene.xml"
onnx_model_path: "models/pupper_ppo_policy_200540160_tf_converted.onnx"

# 核心參數 (Core Parameters)
num_motors: 12
physics_timestep: 0.002
control_freq: 50.0
warmup_duration: 3.0

# 鍵盤控制 (Keyboard Control)
velocity_adjust_step: 0.25 # m/s or rad/s per key press

# ==================================
# === 初始調校參數 (Initial Tuning Parameters)
# ==================================
# 這些值會在程式啟動時載入，但可以在執行時透過鍵盤即時修改
initial_tuning_params:
  kp: 35.0
  kd: 0.50
  action_scale: 0.5
  bias: -45.0

# ==================================
# === 觀察配方 (Observation Recipes)
# ==================================
# Key: ONNX 模型期望的輸入維度
# Value: 構成該維度的觀察元件列表
observation_recipes:
  31:
    - 'z_angular_velocity'
    - 'gravity_vector'
    - 'commands'
    - 'joint_positions'
    - 'last_action'
  48:
    - 'linear_velocity'
    - 'angular_velocity'
    - 'gravity_vector'
    - 'commands'
    - 'joint_positions'
    - 'joint_velocities'
    - 'last_action'