# ==================================
# === 模擬與模型設定 (Simulation & Model Settings)
# ==================================
# 檔案路徑 (File Paths)
mujoco_model_file: "assets/scene_mjx.xml"
# config.yaml

# ==================================
# === 模擬與模型設定 (Simulation & Model Settings)
# ==================================
# ...
# onnx_model_path: "models/pupper_ppo_policy_30965760_tf_converted_穩定步態版.onnx" # 舊的單一模型路徑，可以先註解掉

# ONNX 模型庫 (ONNX Model Library)
onnx_models:
  stable_walk: 
    path: "models/pupper_ppo_policy_30965760_tf_converted_穩定步態版.onnx"
    # 【新】為每個模型指定觀察配方
    observation_recipe:
      - 'linear_velocity'
      - 'angular_velocity'
      - 'gravity_vector'
      - 'joint_positions'
      - 'joint_velocities'
      - 'last_action'
      - 'commands'
  
  agile_model: 
    path: "models/pupper_ppo_policy_200540160_tf_converted.onnx"
    # 假設 agile_model 使用與 stable_walk 相同的配方
    observation_recipe:
      - 'linear_velocity'
      - 'angular_velocity'
      - 'gravity_vector'
      - 'joint_positions'
      - 'joint_velocities'
      - 'last_action'
      - 'commands'

  new_high_level: 
    path: "models/pupper_ppo_policy_203161600_tf_v2.3_converted.onnx"
    # 【新】使用新的觀察配方
    observation_recipe:
      - 'angular_velocity'
      - 'gravity_vector'
      - 'accelerometer'
      - 'joint_positions'
      - 'joint_velocities'
      - 'last_action'
      - 'commands'

  new_e2e: 
    path: "models/pupper_ppo_policy_e2e_203161600.onnx"
    # e2e 模型也使用新的觀察配方
    observation_recipe:
      - 'angular_velocity'
      - 'gravity_vector'
      - 'accelerometer'
      - 'joint_positions'
      - 'joint_velocities'
      - 'last_action'
      - 'commands'

# 模型平滑切換設定
policy_transition_duration: 0.5 # 平滑過渡的持續時間 (秒)
# ==================================

# 核心參數 (Core Parameters)
num_motors: 12
physics_timestep: 0.004 # <-- 建議修改：提高模擬精度以增強穩定性
control_freq: 50.0
warmup_duration: 0.0

# ONNX 模型命令輸入縮放因子
# 順序: [vy 縮放, vx 縮放, wz 縮放]
command_scaling_factors: [1.0, 1.0, 1.0] 

# ==================================
# === 輸入控制設定 (Input Control Settings)
# ==================================
keyboard_velocity_adjust_step: 0.1 # m/s or rad/s per key press

gamepad_sensitivity:
  vx: 1.0   # 前後速度靈敏度 (左搖桿 Y)
  vy: 1.0   # 左右速度靈敏度 (左搖桿 X)
  wz: -1.5  # 轉向角速度靈敏度 (右搖桿 X), 負值表示右推右轉

param_adjust_steps:
  kp: 0.5
  kd: 0.05
  action_scale: 0.05
  bias: 5

# ==================================
# === 初始調校參數 (Initial Tuning Parameters)
# ==================================
initial_tuning_params:
  kp: 2.67  #8000/3000=2.6667
  kd: 0.17 #500/3000=0.1667
  action_scale: 0.5
  bias: -0.0

# ==================================
# === 觀察配方 (Observation Recipes)
# ==================================
#observation_recipes:
#  31:
#    - 'z_angular_velocity'
#    - 'gravity_vector'
#    - 'commands'
#    - 'joint_positions'
#    - 'last_action'
#  48: # <-- 修改這個 48 維的順序
#    - 'linear_velocity'
#    - 'angular_velocity'
#    - 'gravity_vector'
#    - 'joint_positions'
#    - 'joint_velocities'
#    - 'last_action'
#    - 'commands' # <-- 將 commands 移動到最後

# ================================================================= #
# === 懸浮控制器設定 (Floating Controller Settings) - 精細調校版 ===
# ================================================================= #
floating_controller:
  target_height: 0.50     # 懸浮的目標高度 (米)
  kp_vertical: 80.0       # 垂直 P (再次降低以求平滑)
  kd_vertical: 18.0       # 垂直 D (保持與Kp的關係)
  kp_attitude: 20.0       # 姿態 P (再次降低)
  kd_attitude: 4.0        # 姿態 D (相應調整)